return {
  {
    'CopilotC-Nvim/CopilotChat.nvim',
    enabled = false,
    dependencies = {
      { 'zbirenbaum/copilot.lua', opts = {} },
      { 'nvim-lua/plenary.nvim' },
    },
    build = 'make tiktoken',
    opts = {
      prompt = {
        SWETALK = {
          prompt = '',
          system_prompt = 'You are an expert programmer in every programming language, all computer science topics, and optimization techniques',
        },
      },
      -- See Configuration section for options
      model = 'gemini-2.5-pro',
      filetypes = {
        markdown = true,
        help = true,
        gitcommit = true,
        gitrebase = true,
        hgcommit = true,
        svn = true,
        cvs = true,
        ['.'] = false,
        ['python'] = 'python',
        ['lua'] = 'lua',
        ['javascript'] = 'javascript',
        ['javascriptreact'] = 'javascriptreact',
        ['typescript'] = 'typescript',
        ['typescriptreact'] = 'typescriptreact',
        ['rust'] = 'rust',
        ['go'] = 'go',
        ['sh'] = 'sh',
        ['css'] = 'css',
        ['html'] = 'html',
      },
    },
    keys = {
      -- { "<leader>Cc", ":CopilotChat<CR>", mode = "n", desc = "Chat with Copilot" },
      { '<leader>Cc', ':CopilotChatToggle<CR>', mode = 'n', desc = 'Chat with Copilot' },
      { '<leader>Cc', ':CopilotChatToggle<CR>', mode = 'v', desc = 'Chat with Copilot' },
      { '<leader>Ce', ':CopilotChatExplain<CR>', mode = 'v', desc = 'Explain Code' },
      { '<leader>Cr', ':CopilotChatReview<CR>', mode = 'v', desc = 'Review Code' },
      { '<leader>Cf', ':CopilotChatFix<CR>', mode = 'v', desc = 'Fix Code Issues' },
      { '<leader>Co', ':CopilotChatOptimize<CR>', mode = 'v', desc = 'Optimize Code' },
      { '<leader>Cd', ':CopilotChatDocs<CR>', mode = 'v', desc = 'Generate Docs' },
      { '<leader>Ct', ':CopilotChatTests<CR>', mode = 'v', desc = 'Generate Tests' },
      { '<leader>Cm', ':CopilotChatCommit<CR>', mode = 'n', desc = 'Generate Commit Message' },
      { '<leader>Cs', ':CopilotChatCommit<CR>', mode = 'v', desc = 'Generate Commit for Selection' },
      { '<leader>Cv', ':CopilotChatModels<CR>', mode = 'n', desc = 'View/select available models' },
      { '<leader>CS', ':CopilotChatStop<CR>', mode = 'n', desc = 'Stop current output' },
      { '<leader>Cg', ':CopilotChatSave', mode = 'n', desc = 'Save chat history' },
      { '<leader>Cl', ':CopilotChatLoad', mode = 'n', desc = 'Load chat history' },
    },
  },
}
